$schema: http://json-schema.org/draft-06/schema#
$id: product.json
title: Product
description: 製品です。
type: object
required:
  - id
  - name
  - name_kana
  - image
  - size
  - weight_g
  - raw_materials
  - dyeing_materials
additionalProperties: false
dependencies:
  name_alt:
    - name_alt_kana

properties:
  id:
    $ref: '#/definitions/id'
  name:
    $ref: '#/definitions/name'
  name_kana:
    $ref: '#/definitions/name_kana'
  name_alt:
    $ref: '#/definitions/name_alt'
  name_alt_kana:
    $ref: '#/definitions/name_alt_kana'
  image:
    $ref: '#/definitions/image'
  images_alt:
    $ref: '#/definitions/images_alt'
  price:
    $ref: '#/definitions/price'
  links_to_shop:
    $ref: '#/definitions/links_to_shop'
  description:
    $ref: '#/definitions/description'
  size:
    $ref: '#/definitions/size'
  weight_g:
    $ref: '#/definitions/weight_g'
  raw_materials:
    $ref: '#/definitions/raw_materials'
  dyeing_materials:
    $ref: '#/definitions/dyeing_materials'
  notes_maintenance:
    $ref: '#/definitions/maintenance_notes'

definitions:
  id:
    $ref: 'index.json#/definitions/id'
    description: |-
      Product の id です。
      半角アルファベット小文字, 半角数字, ハイフン(-) のみ使用できます。
      この文字列は URI の一部として利用できる必要があります。
    examples:
      - rakuda
      - yama-no-odori
      - akane-ni-tachibana
      - sakeori-no-kaban
  name:
    description: Product の銘となる名前です。
    examples:
      - 駱駝
      - 山の踊り
      - 茜に橘
      - 裂織のかばん
    type: string
  name_kana:
    $ref: 'index.json#/definitions/name_kana'
    description: |-
      Product の name の読み仮名です。
      全角平仮名と半角数字のみ使用できます。
    examples:
      - らくだ
      - やまのおどり
      - あかねにたちばな
      - さきおりのかばん
  name_alt:
    type: string
    description: |-
      Product の別名です。
      省略可能です。
      name_alt が存在する Product は name_alt_kana も必須プロパティになります。
    examples:
      - 草木染め糸のストール
      - 飾る布
      - 草木染色腹帯
  name_alt_kana:
    $ref: 'index.json#/definitions/name_kana'
    description: |-
      Product の名前の読み方を表す仮名です。
      全角平仮名と半角数字のみ使用できます。
      name_alt が存在する Product は name_alt_kana も必須プロパティになります。
    examples:
      - くさきぞめいとのすとーる
      - かざるぬの
      - くさきせんしょくはらおび
  image:
    description: |-
      Product を象徴する画像ファイル URI です。
      URI は RFC3986 に準拠します。
      OGP や JSON-LD などの image の値として利用できる必要があります。
    type: string
    format: uri
    examples:
      - https://houkiboshi.co/products/product-1/images/main.jpg
  images_alt:
    description: |-
      Product の画像ファイル URI のリストです。
      URI は RFC3986 に準拠します。
      image で指定した URI を含める必要はありません。
    type: array
    items:
      type: string
      format: uri
    examples:
      - - https://houkiboshi.co/products/product-1/images/01.jpg
        - https://houkiboshi.co/products/product-1/images/02.jpg
        - https://houkiboshi.co/products/product-1/images/03.jpg
  price:
    description: |-
      Product の日本円価格を表す整数値です。
      非売品・売り切れなどの場合はこのプロパティを省略します。
    type: integer
    minimum: 0
  links_to_shop:
    description: この Product を販売・展示している URI のリストです。
    type: array
    items:
      description: |-
        この Product を販売・展示している URI です。
        URI は RFC3986 に準拠します。
      type: string
      format: uri
      examples:
        - https://minne.com/items/14938131
        - https://www.creema.jp/item/5890223/detail
  description:
    description: Product の説明です。
    type: string
    examples:
      - |-
        水面のような織り柄の布を織りました。
        新書がすっぽり入るくらいの大きさのポーチです。
  size:
    description: |-
      Product のサイズを WDH で表します。
      単位はいずれも mm です。
      参考画像 https://i.imgur.com/Fmfthey.png
    type: object
    required:
      - width_mm
      - depth_mm
    additionalItems: false
    properties:
      width_mm:
        description: |-
          Product を設置してその正面に立ったとき、自分自身から見て横方向の幅を単位 mm で表した整数値です。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 250
      depth_mm:
        description: |-
          Product を設置してその正面に立ったとき、自分自身から見て前方向への奥行きを単位 mm で表した整数値です。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 250
      height_mm:
        description: |-
          Product を設置してその正面に立ったとき、地面からの高さを単位 mm で表した整数値です。
          高さを表記する必要のない Product の場合はこのプロパティを省略します。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 0
      notes:
        description: |-
          サイズについて補足する説明のリストです。
        type: array
        items:
          description: |-
            サイズについて補足する説明文です。
          type: string
          examples:
            - 開口部 約 23 cm
            - 幅計測 フリンジ込み
  weight_g:
    description: Product の重量を単位 g で表した整数値です。
    type: integer
    examples:
      - 52
  raw_materials:
    description: |-
      Product に使用している原材料のリストです。
      参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
    type: array
    items:
      type: object
      required:
        - raw_material_ids
      additionalProperties: false
      properties:
        raw_material_ids:
          description: Raw material の id のリストです。
          type: array
          items:
            $ref: 'raw-material.json#/properties/id'
        used_at:
          description: |-
            この原材料が使われている Product の場所です。
            参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
          type: string
          examples:
            - 表生地
            - 裏生地
        mixing_ratio:
          description: |-
            Product を構成する原材料の混用率です。
            参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
          type: object
          required:
            - percentage
            - decorator
          dependencies:
            decorator:
              - percentage
          properties:
            percentage:
              description: |-
                Product を構成する原材料の混用率を表す整数値です。
                参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
              type: integer
              minimum: 1
              maximum: 100
              examples:
                - 100
                - 50
                - 15
            decorator:
              description: |-
                Product を構成する原材料の混用率に対して '以上' または '未満' の修飾子を追加します。
                '以上' は '>=',
                '未満' は '<',
                何も追加しない場合は '=' の値を取ります。
                percentage が 100 の場合は必ず '=' になります。
                参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
              type: string
              enum:
                - '='
                - '>='
                - '<'
              examples:
                - '='
          if:
            properties:
              percentage:
                const: 100
          then:
            properties:
              decorator:
                enum:
                  - '='
  dyeing_materials:
    description: |-
      Product に使用している染料のリストです。
    type: array
    items:
      description: |-
        Product に使用している染料です。
      type: object
      required:
        - dyeing_material_ids
      properties:
        dyeing_material_ids:
          description: |-
            Dyeing material の id のリストです。
          type: array
          items:
            $ref: 'dyeing-material.json#/properties/id'
        used_at:
          description: |-
            この原材料が使われている Product の場所です。
          type: string
          examples:
            - 表生地
            - 裏生地
  maintenance_notes:
    description: Product の保管・手入れについての説明を補足するテキストのリストです。
    type: array
    items:
      description: Product の保管・手入れについての説明を補足するテキストです。
      type: string
