$schema: http://json-schema.org/draft-06/schema#
$id: product.json
title: Product
description: 製品です。
type: object
required:
  - $schema
  - id
  - name
  - name_kana
  - name_alt
  - name_alt_kana
  - title
  - description
  - body
  - media_image
  - image
  - images_alt
  - price
  - links_to_shop
  - size
  - weight_g
  - raw_materials
  - dyeing_materials
  - process_ids
additionalProperties: false

properties:
  $schema:
    $ref: '#/definitions/$schema'
  id:
    $ref: '#/definitions/id'
  name:
    $ref: '#/definitions/name'
  name_kana:
    $ref: '#/definitions/name_kana'
  name_alt:
    $ref: '#/definitions/name_alt'
  name_alt_kana:
    $ref: '#/definitions/name_alt_kana'
  title:
    $ref: '#/definitions/title'
  description:
    $ref: '#/definitions/description'
  body:
    $ref: '#/definitions/body'
  media_image:
    $ref: '#/definitions/media_image'
  image:
    $ref: '#/definitions/image'
  images_alt:
    $ref: '#/definitions/images_alt'
  price:
    $ref: '#/definitions/price'
  links_to_shop:
    $ref: '#/definitions/links_to_shop'
  size:
    $ref: '#/definitions/size'
  weight_g:
    $ref: '#/definitions/weight_g'
  raw_materials:
    $ref: '#/definitions/raw_materials'
  dyeing_materials:
    $ref: '#/definitions/dyeing_materials'
  process_ids:
    $ref: '#/definitions/process_ids'
  process_entities:
    $ref: '#/definitions/process_entities'
  created_at:
    $ref: 'page.json#/definitions/created_at'
  modified_at:
    $ref: 'page.json#/definitions/modified_at'
  path:
    $ref: 'page.json#/definitions/path'

definitions:
  $schema:
    $ref: '_definitions.json#/definitions/$schema'
    pattern: '(^|/)product\.json$'
    examples:
      - ../../../schemas/product.json
      - https://houkiboshi-fabric.github.io/schema/ref-parsed/product.json
  id:
    $ref: '_definitions.json#/definitions/id'
    examples:
      - rakuda
      - yama-no-odori
      - akane-ni-tachibana
      - sakeori-no-kaban
  name:
    description: Product の銘となる名前です。
    examples:
      - 駱駝
      - 山の踊り
      - 茜に橘
      - 裂織のかばん
    type: string
  name_kana:
    $ref: '_definitions.json#/definitions/name_kana'
    description: |-
      Product の name の読み仮名です。
      全角平仮名と半角数字のみ使用できます。
    examples:
      - らくだ
      - やまのおどり
      - あかねにたちばな
      - さきおりのかばん
  name_alt:
    type: string
    description: |-
      Product の別名です。
      省略可能です。
    examples:
      - 草木染め糸のストール
      - 飾る布
      - 草木染色腹帯
  name_alt_kana:
    $ref: '_definitions.json#/definitions/name_kana'
    description: |-
      Product の名前の読み方を表す仮名です。
      全角平仮名と半角数字のみ使用できます。
    examples:
      - くさきぞめいとのすとーる
      - かざるぬの
      - くさきせんしょくはらおび
  title:
    $ref: 'page.json#/definitions/title'
    examples:
      - 草木染め糸のストール 駱駝
      - 飾る布 山の踊り
  description:
    $ref: 'page.json#/definitions/description'
    examples:
      - |-
        冬に道ばたで見た白い椿がきれいだったので、形にしたいと思って布を染めました。
        内側の布は葛で染めたので、冬の終わりと春の終わりが合体したポーチになりました。
        A4 の紙を三つ折りして入れられるくらいの大きさで、ノートなら B6, A6 が入ります。
  body:
    $ref: 'page.json#/definitions/body'
  media_image:
    $ref: 'page.json#/definitions/media_image'
    examples:
      - products/product-1/media.jpg
  image:
    description: |-
      この Product を象徴するメイン画像のファイルパスです。
      assets repository からオリジナル画像を取得する際に利用します。
      フォーマットは RFC3986 Section-4.1 に準拠する相対パスです。
      参考 https://tools.ietf.org/html/rfc3986#section-4.1
      画像がない場合は null を指定します。
    oneOf:
      - type: string
        format: uri-reference
      - type: 'null'
    examples:
      - products/product-1/main.jpg
  images_alt:
    description: |-
      この Product の画像ファイルパスのリストです。
      assets repository からオリジナル画像を取得する際に利用します。
      フォーマットは RFC3986 Section-4.1 に準拠する相対パスです。
      参考 https://tools.ietf.org/html/rfc3986#section-4.1
      image プロパティで指定したパスを含める必要はありません。
      画像がない場合は空の配列を指定します。
    type: array
    uniqueItems: true
    items:
      type: string
      format: uri-reference
      examples:
        - products/product-1/01.jpg
        - products/product-1/02.jpg
        - products/product-1/03.jpg
    examples:
      - []
      - - products/product-1/01.jpg
        - products/product-1/02.jpg
        - products/product-1/03.jpg
  price:
    description: |-
      Product の日本円価格を表す整数値です。
      非売品・売り切れなどの場合は null を指定します。
    oneOf:
      - type: integer
        minimum: 0
      - type: 'null'
    examples:
      - 100000
      - null
  links_to_shop:
    description: |-
      この Product を販売・展示している URI のリストです。
      URI がひとつもない場合は空の配列を指定します。
    type: array
    uniqueItems: true
    examples:
      - []
      - - https://minne.com/items/14938131
        - https://www.creema.jp/item/5890223/detail
    items:
      description: |-
        この Product を販売・展示している URI です。
        URI は RFC3986 に準拠します。
      type: string
      format: uri
      examples:
        - https://minne.com/items/14938131
        - https://www.creema.jp/item/5890223/detail
  size:
    description: |-
      Product のサイズを WDH で表します。
      単位はいずれも mm です。
      参考画像 https://i.imgur.com/Fmfthey.png
    type: object
    required:
      - width_mm
      - depth_mm
    additionalProperties: false
    examples:
      - width_mm: 250
        depth_mm: 250
      - width_mm: 250
        depth_mm: 250
        height_mm: 250
    properties:
      width_mm:
        description: |-
          Product を設置してその正面に立ったとき、自分自身から見て横方向の幅を単位 mm で表した整数値です。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 250
      depth_mm:
        description: |-
          Product を設置してその正面に立ったとき、自分自身から見て前方向への奥行きを単位 mm で表した整数値です。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 250
      height_mm:
        description: |-
          Product を設置してその正面に立ったとき、地面からの高さを単位 mm で表した整数値です。
          高さを表記する必要のない Product の場合はこのプロパティを省略します。
          参考画像 https://i.imgur.com/Fmfthey.png
        type: integer
        minimum: 0
        examples:
          - 0
      notes:
        description: |-
          サイズについて補足する説明のリストです。
          最低 1 つの説明を含む配列である必要があります。
        type: array
        uniqueItems: true
        minItems: 1
        items:
          description: |-
            サイズについて補足する説明文です。
          type: string
          examples:
            - 開口部 約 23 cm
            - 幅計測 フリンジ込み
  weight_g:
    description: Product の重量を単位 g で表した整数値です。
    type: integer
    examples:
      - 52
  raw_materials:
    description: |-
      Product に使用している原材料のリストです。
      参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
    type: array
    uniqueItems: true
    examples:
      - - raw_material_ids:
            - cotton
          used_at: 表生地
          mixing_ratio:
            percentage: 100
            decorator: =
        - raw_material_ids:
            - wool
          used_at: 裏生地
          mixing_ratio:
            percentage: 100
            decorator: =
    items:
      type: object
      required:
        - raw_material_ids
      additionalProperties: false
      examples:
        - raw_material_ids:
            - cotton
      properties:
        raw_material_ids:
          description: Raw material の id のリストです。
          type: array
          uniqueItems: true
          items:
            $ref: 'raw-material.json#/properties/id'
        raw_material_entities:
          description: |-
            raw_material_ids を元に参照した Raw material のリストです。
            このプロパティはビルドタスクなどで自動的に追加するユースケースを想定しています。
          type: array
          uniqueItems: true
          items:
            $ref: 'raw-material.json'
            $id: 'raw-material-entity-in-product'
        used_at:
          description: |-
            この原材料が使われている Product の場所です。
            参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
          type: string
          examples:
            - 表生地
            - 裏生地
        mixing_ratio:
          description: |-
            Product を構成する原材料の混用率です。
            参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
          type: object
          required:
            - percentage
            - decorator
          additionalProperties: false
          dependencies:
            decorator:
              - percentage
          examples:
            - percentage: 100
              decorator: =
          properties:
            percentage:
              description: |-
                Product を構成する原材料の混用率を表す整数値です。
                参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
              type: integer
              minimum: 1
              maximum: 100
              examples:
                - 100
                - 50
                - 15
            decorator:
              description: |-
                Product を構成する原材料の混用率に対して '以上' または '未満' の修飾子を追加します。
                '以上' は '>=',
                '未満' は '<',
                何も追加しない場合は '=' の値を取ります。
                percentage が 100 の場合は必ず '=' になります。
                参照) 繊維製品の表示について｜消費者庁 http://www.caa.go.jp/policies/policy/representation/household_goods/guide/fiber/fiber_show.html
              type: string
              enum:
                - '='
                - '>='
                - '<'
              examples:
                - '='
          if:
            properties:
              percentage:
                const: 100
          then:
            properties:
              decorator:
                enum:
                  - '='
          else:
            properties:
              decorator:
                enum:
                  $ref: '#/definitions/raw_materials/items/properties/mixing_ratio/properties/decorator/enum'
  dyeing_materials:
    description: |-
      Product に使用している染料のリストです。
    type: array
    uniqueItems: true
    examples:
      - - dyeing_material_ids:
            - cherry
          used_at: 表生地
        - dyeing_material_ids:
            - madder
            - mint
          used_at: 裏生地
    items:
      description: |-
        Product に使用している染料です。
      type: object
      examples:
        - dyeing_material_ids:
            - cherry
          used_at: 表生地
      required:
        - dyeing_material_ids
      additionalProperties: false
      properties:
        dyeing_material_ids:
          description: |-
            Dyeing material の id のリストです。
          type: array
          uniqueItems: true
          items:
            $ref: 'dyeing-material.json#/properties/id'
        dyeing_material_entities:
          description: |-
            dyeing_material_ids を元に参照した Dyeing material のリストです。
            このプロパティはビルドタスクなどで自動的に追加するユースケースを想定しています。
          type: array
          uniqueItems: true
          items:
            $ref: 'dyeing-material.json'
            $id: 'dyeing-material-entity-in-product'
        used_at:
          description: |-
            この原材料が使われている Product の場所です。
          type: string
          examples:
            - 表生地
            - 裏生地
  process_ids:
    description: |-
      この Product の製法を表す Process id のリストです。
    type: array
    uniqueItems: true
    examples:
      - - process-kusaki-zome
        - process-hand-spinning
    items:
      $ref: 'process.json#/properties/id'
  process_entities:
    description: |-
      process_ids を元に参照した Process のリストです。
      このプロパティはビルドタスクなどで自動的に追加するユースケースを想定しています。
    type: array
    uniqueItems: true
    items:
      $ref: 'process.json'
      $id: 'process-entity-in-product'
